name: DEPLOY AWS LAMBDA
on:
  push:
    branches:
      - master
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - name: Step 1 - Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: Step 2 - Configure Node - Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Step 3 - Install Dependencies
        run: npm install
      # - name: Step 4 - Run Tests
      #   run: npm run test
      - name: Step 5 - Serverless Deploy DEVELOPMENT
        if: "${{ github.ref_name == 'develop' }}"
        uses: serverless/github-action@v2
        with:
          args: -c "serverless plugin install --name serverless-esbuild && serverless deploy --stage dev -v"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI_DEV }}
          JSREPORT_USER: ${{ secrets.JSREPORT_USER }}
          JSREPORT_PASSWORD: ${{ secrets.JSREPORT_PASSWORD }}
          JSREPORT_URL: ${{ secrets.JSREPORT_URL }}
          JSREPORT_CERTIFICATE_SHORT_ID: ${{ secrets.JSREPORT_CERTIFICATE_SHORT_ID }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME_DEV }}
      - name: Step 5 - Serverless Deploy PRODUCTION
        if: "${{ github.ref_name == 'master' }}"
        uses: serverless/github-action@v2
        with:
          args: -c "serverless plugin install --name serverless-esbuild && serverless deploy --stage prod -v"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI_PROD }}
          JSREPORT_USER: ${{ secrets.JSREPORT_USER }}
          JSREPORT_PASSWORD: ${{ secrets.JSREPORT_PASSWORD }}
          JSREPORT_URL: ${{ secrets.JSREPORT_URL }}
          JSREPORT_CERTIFICATE_SHORT_ID: ${{ secrets.JSREPORT_CERTIFICATE_SHORT_ID }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME_PROD }}
